# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='profilepics'),
        ),
    ]
