# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20171124_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='coverpic',
            field=models.ImageField(blank=True, upload_to='overpics'),
        ),
    ]
