# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='duration',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
