# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auctions_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='duration',
            field=models.DateTimeField(),
        ),
    ]
