# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_comments_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.SellItemInfo'),
            preserve_default=False,
        ),
    ]
