# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20171228_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selliteminfo',
            name='item_exprice',
            field=models.IntegerField(),
        ),
    ]
