# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_serverinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='video',
            field=models.URLField(),
        ),
    ]
