# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20171124_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverinfo',
            old_name='video',
            new_name='videos',
        ),
    ]
