# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 17:54
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20171124_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='videos',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
