# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20171124_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='videos',
            field=models.URLField(),
        ),
    ]
