# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='selliteminfo',
            name='isAuction',
            field=models.BooleanField(default=False),
        ),
    ]
