# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 16:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_selliteminfo_isauction'),
    ]

    operations = [
        migrations.AddField(
            model_name='selliteminfo',
            name='timestemp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 29, 16, 28, 2, 917166, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
