# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_selliteminfo_timestemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selliteminfo',
            name='item_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('guiter', 'Guiter'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('camera', 'Camera'), ('console', 'Console')], default='phone', max_length=6),
        ),
    ]
